# Generated by Django 5.0.4 on 2024-05-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('CREADA', 'Creada'), ('DESARROLLO', 'Desarrollo'), ('COMPLETADA', 'Completada')], default='CREADA', max_length=20)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaLimite', models.DateTimeField()),
            ],
        ),
    ]
